# Generated by Django 5.0.14 on 2026-09-12 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataHistoris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desil', models.PositiveSmallIntegerField()),
                ('jumlah_tanggungan', models.PositiveSmallIntegerField()),
                ('penghasilan', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DITERIMA', 'Diterima'), ('DITOLAK', 'Ditolak')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='JenisBantuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bantuan', models.CharField(max_length=150)),
                ('deskripsi', models.TextField(blank=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pengajuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_tanggungan', models.PositiveSmallIntegerField()),
                ('penghasilan', models.PositiveIntegerField(help_text='Rupiah per bulan')),
                ('desil', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tanggal_pengajuan', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('MENUNGGU_VERIFIKASI_DESIL', 'Menunggu Verifikasi Desil'), ('REKOMENDASI_TERSEDIA', 'Rekomendasi Tersedia'), ('DISETUJUI', 'Disetujui'), ('DITOLAK', 'Ditolak')], default='MENUNGGU_VERIFIKASI_DESIL', max_length=30)),
                ('jenis_bantuan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pengajuan_list', to='pengajuan.jenisbantuan')),
            ],
        ),
        migrations.CreateModel(
            name='HasilPrediksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediksi', models.CharField(choices=[('LAYAK', 'Layak'), ('TIDAK_LAYAK', 'Tidak Layak')], max_length=20)),
                ('probabilitas', models.FloatField(help_text='Probabilitas kelas prediksi, 0-1')),
                ('model_digunakan', models.CharField(help_text='mis. decision_tree_v1', max_length=50)),
                ('tanggal_prediksi', models.DateTimeField(auto_now_add=True)),
                ('pengajuan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hasil_prediksi', to='pengajuan.pengajuan')),
            ],
        ),
        migrations.CreateModel(
            name='Verifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keputusan', models.CharField(choices=[('DISETUJUI', 'Disetujui'), ('DITOLAK', 'Ditolak')], max_length=20)),
                ('catatan', models.TextField(blank=True)),
                ('tanggal_verifikasi', models.DateTimeField(auto_now_add=True)),
                ('pengajuan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verifikasi', to='pengajuan.pengajuan')),
                ('validator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verifikasi_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Warga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('nik', models.CharField(max_length=16, unique=True)),
                ('rt', models.CharField(max_length=5)),
                ('rw', models.CharField(max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warga_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pengajuan',
            name='warga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajuan_list', to='pengajuan.warga'),
        ),
    ]
